spring.application.name=projetoAWS

# Credenciais AWS
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
spring.cloud.aws.region.static=us-east-1

# Nome da sua fila (Criada na Fase 2)
aws.sqs.dlq-name=T02N_FLAVIO_ANTONIO_GIORDANI_SCHNEIDER-DLQ.fifo

# H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

